version: '3'

services:
  app:
    container_name: app
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://app:changethispassword@database:3306/api_plateform?serverVersion=8&charset=utf8mb4
    build: .
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/var
      - /var/www/node_modules
      - /var/www/public
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8000:80"

  database:
    image: mysql/mysql-server:8.0
#    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: api_plateform
#      # So you don't have to use root, but you can if you like
      MYSQL_USER: app
#      # You can use whatever password you like
      MYSQL_PASSWORD: changethispassword
      # Password for root access
      MYSQL_ROOT_PASSWORD: changethispassword
    expose:
      # Opens port 3306 on the container
      - "3306:3306"
    networks:
      - default

networks:
  dev: